config/routes.rb
Rails.application.routes.draw do
  resources :directorios
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/directorio.rb
class Directorio < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/directorios_controller.rb
class DirectoriosController < ApplicationController
  before_action :set_directorio, only: [:show, :edit, :update, :destroy]

  # GET /directorios
  # GET /directorios.json
  def index
    @directorios = Directorio.all
  end

  # GET /directorios/1
  # GET /directorios/1.json
  def show
  end

  # GET /directorios/new
  def new
    @directorio = Directorio.new
  end

  # GET /directorios/1/edit
  def edit
  end

  # POST /directorios
  # POST /directorios.json
  def create
    @directorio = Directorio.new(directorio_params)

    respond_to do |format|
      if @directorio.save
        format.html { redirect_to @directorio, notice: 'Directorio was successfully created.' }
        format.json { render :show, status: :created, location: @directorio }
      else
        format.html { render :new }
        format.json { render json: @directorio.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /directorios/1
  # PATCH/PUT /directorios/1.json
  def update
    respond_to do |format|
      if @directorio.update(directorio_params)
        format.html { redirect_to @directorio, notice: 'Directorio was successfully updated.' }
        format.json { render :show, status: :ok, location: @directorio }
      else
        format.html { render :edit }
        format.json { render json: @directorio.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /directorios/1
  # DELETE /directorios/1.json
  def destroy
    @directorio.destroy
    respond_to do |format|
      format.html { redirect_to directorios_url, notice: 'Directorio was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_directorio
      @directorio = Directorio.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def directorio_params
      params.require(:directorio).permit(:nombre, :apellido, :telefono)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/directorios_helper.rb
module DirectoriosHelper
end

app/views/directorios/_form.html.erb
<%= form_with(model: directorio, local: true) do |form| %>
  <% if directorio.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(directorio.errors.count, "error") %> prohibited this directorio from being saved:</h2>

      <ul>
      <% directorio.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre, id: :directorio_nombre %>
  </div>

  <div class="field">
    <%= form.label :apellido %>
    <%= form.text_field :apellido, id: :directorio_apellido %>
  </div>

  <div class="field">
    <%= form.label :telefono %>
    <%= form.number_field :telefono, id: :directorio_telefono %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/directorios/edit.html.erb
<h1>Editing Directorio</h1>

<%= render 'form', directorio: @directorio %>

<%= link_to 'Show', @directorio %> |
<%= link_to 'Back', directorios_path %>

app/views/directorios/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Directorios</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Apellido</th>
      <th>Telefono</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @directorios.each do |directorio| %>
      <tr>
        <td><%= directorio.nombre %></td>
        <td><%= directorio.apellido %></td>
        <td><%= directorio.telefono %></td>
        <td><%= link_to 'Show', directorio %></td>
        <td><%= link_to 'Edit', edit_directorio_path(directorio) %></td>
        <td><%= link_to 'Destroy', directorio, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Directorio', new_directorio_path %>

app/views/directorios/new.html.erb
<h1>New Directorio</h1>

<%= render 'form', directorio: @directorio %>

<%= link_to 'Back', directorios_path %>

app/views/directorios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @directorio.nombre %>
</p>

<p>
  <strong>Apellido:</strong>
  <%= @directorio.apellido %>
</p>

<p>
  <strong>Telefono:</strong>
  <%= @directorio.telefono %>
</p>

<%= link_to 'Edit', edit_directorio_path(@directorio) %> |
<%= link_to 'Back', directorios_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Agenda</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>